version: '3.8'

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - app-tapgoods-wp:/var/www/html/wp-content/plugins/tapgoods-wp
    extra_hosts:
      - wordpress.local:host-gateway
    env_file:
    - localdev.env

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
    - db:mysql
    ports:
      - '8181:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - app-nginx:/etc/nginx
      - app-dev-certs:/etc/nginx/certs
    depends_on:
      - wordpress

  wpcli:
    image: wordpress:cli
    command: "wp --info"
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - app-tapgoods-wp:/var/www/html/wp-content/plugins/tapgoods-wp
    depends_on:
      - db
      - wordpress

  composer:
      image: composer/composer
      working_dir: /var/www/html/wp-content/plugins/tapgoods-wp
      command: "install"
      restart: 'no'
      volumes:
        - wordpress:/var/www/html:rw,cache
        - app-tapgoods-wp:/var/www/html/wp-content/plugins/tapgoods-wp
      depends_on:
        - wordpress

  # generate-certs:
  #   image: ubuntu:20.04
  #   entrypoint: /bin/sh
  #   command: ./generate-certs.sh
  #   profiles:
  #     - "doNotStart"
  #   volumes:
  #     - ./dev/generate-certs.sh:/generate-certs.sh:rw
  #     - ./dev/certs:/certs:rw

volumes:
  wordpress:
  db:
  nginx-config:
  app-tapgoods-wp:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/tapgoods-wp
      o: bind
  app-nginx:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/dev/conf
      o: bind
  app-dev-certs:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/dev/certs
      o: bind            