name: Package WordPress Plugin

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build and Zip plugin
        run: |
          npm run build
          npm run zip-plugin

      - name: Commit and push the releases folder
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add releases || true
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Add generated plugin zip to releases folder"
            git push origin master
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
