name: Package WordPress Plugin

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Bump version in tapgoods-wp/tapgoods.php and readme.txt
        run: |
          # Find current version
          current_version=$(grep -oP 'Version:\s*\K[\d.]+' tapgoods-wp/tapgoods.php)
          echo "Current version: $current_version"

          # Increment version by 0.0.1
          new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF = $NF + 1 ; print}')
          echo "New version: $new_version"

          # Replace the version in tapgoods.php
          sed -i "s/Version:\s*$current_version/Version:           $new_version/" tapgoods-wp/tapgoods.php

          # Replace the stable tag in readme.txt
          sed -i "s/Stable tag:\s*$current_version/Stable tag: $new_version/" tapgoods-wp/readme.txt

          # Commit the version change
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add tapgoods-wp/tapgoods.php tapgoods-wp/readme.txt
          git commit -m "Bump version to $new_version"
          git push origin master

      - name: Build and Zip plugin
        run: |
          npm run build
          npm run zip-plugin

      - name: Commit and push the releases folder
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add releases || true
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Add generated plugin zip to releases folder"
            git push origin master
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
